name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install all dependencies
        run: yarn install
      - name: Build and test
        run: yarn test
